version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - restore_cache: #保存されたキャッシュを復元します。
          key: composer-v1-{{ checksum "composer.lock" }} #復元するキャッシュの名前を指定
      - run: composer install -n --prefer-dist #Composerを使用してPHP関連パッケージをインストール
      - save_cache: #keyに指定した名前でキャッシュを保存します。
          key: composer-v1-{{ checksum "composer.lock" }} #CircleCIのテンプレート機能. {{ checksum "ファイル名" }}とすることで、ファイルをハッシュ化した値を算出
          paths:  #保存するディレクトリ名やファイル名はpathsに指定
            - vendor #ComposerによってPHP関連のパッケージがインストールされるディレクトリであるvendorを指定
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}  
      - run:
          name: npm ci #npmを使用してJavaScript関連パッケージ
          #ifを逆さまに記述したfiは、if文の終わりを示しており、必須
          #[ -d node_modules ]という書き方をすると、node_modulesというディレクトリが存在すればtrueを、存在しなければfalseを返します。
          command: |
            if [ ! -d node_modules ]; then 
              npm ci
            fi 
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules #pathsに指定したnode_modulesをキャッシュに保存
      - run: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit